import type { Metadata } from "next";
import { Geist, Geist_Mono, Unbounded } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const unbounded = Unbounded({
  subsets: ["latin"],
  weight: ["700"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        style={{
          backgroundImage: "url('/BACKGROUND.png')",
          backgroundSize: 'cover',
          backgroundPosition: 'center',
          backgroundRepeat: 'no-repeat',
        }}
      >
        <main className="h-screen flex flex-col items-center justify-center p-8">
          <h1 className={`${unbounded.className} text-8xl font-bold text-black mb-4`}>
            TRIO
          </h1>
          <div className="relative w-[90%] h-[75%] flex items-center justify-center bg-white/10 backdrop-blur-sm rounded-[50px] p-6 overflow-hidden">
            {children}
          </div>
        </main> 
      </body>
    </html>
  );
}