import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "@/app/globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        style={{
          backgroundImage: "url('/BACKGROUND.png')",
          backgroundSize: 'cover',
          backgroundPosition: 'center',
          backgroundRepeat: 'no-repeat',
        }}
      >
        <main className="flex min-h-screen flex-col items-center justify-center p-24">
            <div className="bg-white/10 backdrop-blur-sm rounded-[50px] p-4 sm:p-6 md:p-8 
            w-[95%] md:w-[90%] lg:w-[80%] xl:w-[1000px] 
            max-h-[90vh] lg:max-h-[600px] 
            border border-white/20">
            {children}
            </div>
        </main> 
      </body>
    </html>
  );
}
